steps:
- name: node
  entrypoint: yarn
  args: ['install']
- name: node
  entrypoint: yarn
  args: ['build']
- name: 'bash'
  args: ['ls', '-R', 'build/']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - emails
  - --runtime=nodejs16
  - --source=.
  - --trigger-http
